import type { Metadata } from "next";
import "@/shared/styles/colors.css";
import "@/shared/styles/typography.css";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const wantedSans = localFont({src: '../assets/fonts/WantedSansVariable.woff2'});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={wantedSans.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
